# Generated by Django 3.0.2 on 2020-03-31 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_overall_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_ratings',
            name='ISBN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Ratings'),
        ),
    ]
