# Generated by Django 3.0.2 on 2020-04-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20200331_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_ratings',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Books'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='overall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Overall_Ratings'),
        ),
    ]
