# Generated by Django 3.0.2 on 2020-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20200401_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='ratings',
            name='Username',
            field=models.CharField(default='foobar', max_length=50),
            preserve_default=False,
        ),
    ]
