# Generated by Django 3.0.2 on 2020-01-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.PositiveIntegerField()),
                ('Book_Title', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Year_Of_Publication', models.PositiveIntegerField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Image_URL_M', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.PositiveIntegerField()),
                ('ISBN', models.PositiveIntegerField()),
                ('BookRating', models.PositiveIntegerField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Upload.Books')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Upload.Users')),
            ],
        ),
    ]
