# Generated by Django 3.0.2 on 2020-01-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0004_auto_20200127_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100)),
                ('Book_Title', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Year_Of_Publication', models.PositiveIntegerField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Image_URL_M', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Upload.Books'),
        ),
    ]
