# Generated by Django 3.0.2 on 2020-01-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0005_auto_20200127_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
