# Generated by Django 3.0.2 on 2020-01-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0007_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='users',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
