# Generated by Django 3.0.2 on 2020-01-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0009_auto_20200128_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='books',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='users',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
