# Generated by Django 3.0.2 on 2020-02-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0011_auto_20200129_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='books',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='users',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
