# Generated by Django 3.0.2 on 2020-02-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Upload', '0012_auto_20200203_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100)),
                ('Book_Title', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Year_Of_Publication', models.PositiveIntegerField()),
                ('Publisher', models.CharField(max_length=100)),
                ('Image_URL_M', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.PositiveIntegerField()),
                ('Age', models.PositiveIntegerField()),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.PositiveIntegerField()),
                ('ISBN', models.CharField(max_length=100)),
                ('Book_Rating', models.PositiveIntegerField()),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Upload.Books')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Upload.Users')),
            ],
        ),
    ]
