# Generated by Django 3.0.2 on 2020-02-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0013_books_ratings_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='books',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
