# Generated by Django 3.0.2 on 2020-02-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0015_auto_20200203_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
