# Generated by Django 3.0.2 on 2020-03-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0019_books_ratings_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='books',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='users',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
